omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com
omnitools.download class_object class_scene depth_euclidean depth_zbuffer edge_occlusion edge_texture keypoints2d keypoints3d nonfixated_matches normal points principal_curvature reshading rgb segment_semantic segment_unsup2d segment_unsup25d --components taskonomy --subset tiny --dest ./taskonomy_tiny/   --connections_total 40 --agree --name Zitian --email tankche2@gmail.com


# rgb/taskonomy/klickitat depth_euclidean/taskonomy/lakeville depth_zbuffer/taskonomy/lakeville edge_occlusion/taskonomy/lakeville edge_texture/taskonomy/lakeville keypoints2d/taskonomy/lakeville keypoints3d/taskonomy/lakeville normal/taskonomy/lakeville principal_curvature/taskonomy/lakeville rgb/taskonomy/benevolence depth_euclidean/taskonomy/coffeen depth_zbuffer/taskonomy/coffeen edge_occlusion/taskonomy/coffeen edge_texture/taskonomy/coffeen keypoints2d/taskonomy/coffeen keypoints3d/taskonomy/coffeen normal/taskonomy/coffeen edge_texture/taskonomy/mifflinburg keypoints3d/taskonomy/mifflinburg normal/taskonomy/mifflinburg principal_curvature/taskonomy/mifflinburg reshading/taskonomy/mifflinburg rgb/taskonomy/mifflinburg edge_texture/taskonomy/wiconisco
rgb/taskonomy/klickitat
edge_texture/taskonomy/lakeville
keypoints3d/taskonomy/lakeville
normal/taskonomy/lakeville
principal_curvature/taskonomy/lakeville
edge_texture/taskonomy/coffeen
edge_texture/taskonomy/mifflinburg
keypoints3d/taskonomy/mifflinburg
normal/taskonomy/mifflinburg
principal_curvature/taskonomy/mifflinburg
reshading/taskonomy/mifflinburg
rgb/taskonomy/mifflinburg
edge_texture/taskonomy/wiconisco